# Data Cleaning and Preprocessing

## Customer Shopping Behavior Dataset

### Objective

The purpose of this notebook is to clean and preprocess the raw customer
shopping behavior dataset before analysis and modeling.

The following preprocessing steps will be performed:

- Handling missing values
- Checking duplicate records
- Standardizing column names
- Correcting inconsistent category mappings
- Improving data quality and consistency
- Preparing the dataset for further analysis and report

In [1]:
# Import libraries for data manipulation, visualization, and database operations

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sqlalchemy import create_engine, text, inspect

# Improve chart appearance
sns.set_style("whitegrid")

In [2]:
# Load the raw customer shopping dataset

df = pd.read_csv("../data/raw/customer_shopping_behavior.csv")

# Display first 5 rows of the dataset
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [3]:
# Check total rows and columns in the dataset

df.shape

(5050, 17)

In [4]:
# Inspect dataset structure, datatypes, and non-null counts

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 17 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   str
 3   Item Purchased          5050 non-null   str
 4   Category                5050 non-null   str
 5   Purchase Amount (USD)   4494 non-null   float64
 6   Location                5050 non-null   str
 7   Size                    4680 non-null   str
 8   Color                   5050 non-null   str
 9   Season                  5050 non-null   str
 10  Review Rating           4449 non-null   float64
 11  Subscription Status     5050 non-null   str
 12  Shipping Type           5050 non-null   str
 13  Discount Applied        5050 non-null   str
 14  Previous Purchases      4502 non-null   float64
 15  Payment Method          5050 non-null   str
 16  Frequency of Purchases  5050 non-null   str
dtypes: float64(3), int64(2), str(12)
memory usage: 670.8 KB

In [5]:
# Generate statistical summary of numerical columns

df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [6]:
# Identify missing values in each column

df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [7]:
# Display all column names

df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='str')

In [8]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('_(usd)', ''))

df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='str')

In [9]:
# Display all rows and columns without truncation

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [10]:
df.groupby('category')['item_purchased'].unique()

category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: item_purchased, dtype: object

In [11]:
# Create correct category mapping based on purchased items
correct_mapping = {
    # Clothing
    'T-shirt': 'Clothing',
    'Shirt': 'Clothing',
    'Shorts': 'Clothing',
    'Hoodie': 'Clothing',
    'Pants': 'Clothing',
    'Socks': 'Clothing',
    'Jeans': 'Clothing',
    'Blouse': 'Clothing',
    'Skirt': 'Clothing',
    'Sweater': 'Clothing',
    'Dress': 'Clothing',

    # Accessories
    'Sunglasses': 'Accessories',
    'Gloves': 'Accessories',
    'Jewelry': 'Accessories',
    'Hat': 'Accessories',
    'Handbag': 'Accessories',
    'Backpack': 'Accessories',
    'Belt': 'Accessories',
    'Scarf': 'Accessories',
    'Bag': 'Accessories',

    # Electronics
    'Laptop': 'Electronics',
    'Phone': 'Electronics',
    'Headphones': 'Electronics',
    'Watch': 'Electronics',

    # Footwear
    'Shoes': 'Footwear',
    'Sandals': 'Footwear',
    'Sneakers': 'Footwear',
    'Boots': 'Footwear',

    # Outerwear
    'Coat': 'Outerwear',
    'Jacket': 'Outerwear'
}

In [12]:
# Update category column using correct item-category mapping

df['category'] = df['item_purchased'].map(correct_mapping)

# Preview updated data
# Check items grouped by category to identify incorrect category mapping

df.groupby('category')['item_purchased'].unique()

category
Accessories                 [Sunglasses, Gloves, Jewelry, Hat, Handbag, Backpack, Bag, Belt, Scarf]
Clothing       [T-shirt, Shirt, Shorts, Hoodie, Pants, Socks, Jeans, Blouse, Skirt, Sweater, Dress]
Electronics                                                      [Laptop, Phone, Watch, Headphones]
Footwear                                                          [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                            [Coat, Jacket]
Name: item_purchased, dtype: object

In [13]:
# Check missing values after category correction

df.isnull().sum()

customer_id                 0
age                         0
gender                      0
item_purchased              0
category                    0
purchase_amount           556
location                    0
size                      370
color                       0
season                      0
review_rating             601
subscription_status         0
shipping_type               0
discount_applied            0
previous_purchases        548
payment_method              0
frequency_of_purchases      0
dtype: int64

### Treating Missing Values in size

In [14]:
# Check size values across each category

df.groupby('category')['size'].unique()

category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: size, dtype: object

In [15]:
# Fill size values for Electronics category since electronic products
# do not have clothing-related size measurements

df.loc[df['category'] == 'Electronics', 'size'] = 'Not Applicable'

In [16]:
# Replace missing size values in Accessories category
# since most accessories are generally available in free size

df.loc[df['category'] == 'Accessories', "size"] = "Free Size"

In [17]:
# Replace size values in Footwear category since footwear
# does not follow standard clothing size formats like S, M, or XL

df.loc[df["category"] == "Footwear", "size"] = "Not Available"

In [18]:
# Find most common size value for Clothing category

clothing_mode = df[df['category'] == 'Clothing']['size'].mode()[0]

In [19]:
# Fill missing size values in Clothing category
# using the most frequently occurring clothing size

df.loc[
    (df['category'] == 'Clothing')& (df['size'].isnull()), 'size'
] = clothing_mode

In [20]:
# Fill missing size values in Clothing category
# using the most frequently occurring clothing size

df.loc[
    (df["category"] == "Clothing") & (df["size"].isnull()),
    "size"
] = clothing_mode

In [21]:
# Inspect unique size values across each product category

df.groupby('category')['size'].unique()

category
Accessories         [Free Size]
Clothing          [XL, M, S, L]
Electronics    [Not Applicable]
Footwear        [Not Available]
Outerwear         [XL, L, S, M]
Name: size, dtype: object

### Treating Missing Values in review_rating

In [22]:
# Check mean, median, and mode of review_rating column

print(f'Mean: {df['review_rating'].mean()}')
print(f'Mean: {df['review_rating'].median()}')
print(f'Mean: {df['review_rating'].mode()[0]}')

Mean: 3.668195100022477
Mean: 3.7
Mean: 4.0

In [23]:
# Check average review rating by item purchased

df.groupby('item_purchased')['review_rating'].mean()

item_purchased
Backpack      3.758333
Bag           3.168539
Belt          3.762963
Blouse        3.677647
Boots         3.813194
Coat          3.721875
Dress         3.750000
Gloves        3.862774
Handbag       3.771975
Hat           3.796753
Headphones    3.075949
Hoodie        3.716779
Jacket        3.761446
Jeans         3.651969
Jewelry       3.761850
Laptop        3.191176
Pants         3.720833
Phone         2.939024
Sandals       3.837037
Scarf         3.702564
Shirt         3.427273
Shoes         3.546154
Shorts        3.722981
Skirt         3.779747
Sneakers      3.757931
Socks         3.755063
Sunglasses    3.745679
Sweater       3.768712
T-shirt       3.790541
Watch         3.100000
Name: review_rating, dtype: float64

In [24]:
# Fill missing review_rating values using average rating of each item

df['review_rating'] = df['review_rating'].fillna(
    df.groupby('item_purchased')['review_rating'].transform('mean')
)

In [25]:
# Round review_rating values to 2 decimal places

df["review_rating"] = df["review_rating"].round(2)

In [26]:
# Check missing values after treating review_rating column

df["review_rating"].isnull().sum()

np.int64(0)

### Treating Missing Values in previous_purchases

In [27]:
### Treating Missing Values in previous_purchases with 0

df['previous_purchases'] = df['previous_purchases'].fillna(0)

# Veryfying

df["previous_purchases"].isnull().sum()

np.int64(0)

In [28]:
df.isnull().sum()

customer_id                 0
age                         0
gender                      0
item_purchased              0
category                    0
purchase_amount           556
location                    0
size                        0
color                       0
season                      0
review_rating               0
subscription_status         0
shipping_type               0
discount_applied            0
previous_purchases          0
payment_method              0
frequency_of_purchases      0
dtype: int64

### Treating Missing Values in purchase_amount

In [29]:
# Check average purchase amount by item purchased

df.groupby("item_purchased")["purchase_amount"].mean()

item_purchased
Backpack       60.111111
Bag           735.773625
Belt           59.993902
Blouse         60.802326
Boots          62.616438
Coat           57.851852
Dress          62.168675
Gloves         60.550000
Handbag        57.987261
Hat            60.787097
Headphones    831.344565
Hoodie         58.059603
Jacket         56.777108
Jeans          60.456693
Jewelry        59.011494
Laptop        805.502027
Pants          59.005848
Phone         734.477349
Sandals        57.527607
Scarf          61.157233
Shirt         279.935608
Shoes         276.343790
Shorts         60.073620
Skirt          59.723270
Sneakers       59.551724
Socks          58.188679
Sunglasses     59.975610
Sweater        57.638554
T-shirt        63.093333
Watch         685.231471
Name: purchase_amount, dtype: float64

In [30]:
# Fill missing purchase_amount values using average amount of each item

df["purchase_amount"] = df["purchase_amount"].fillna(
    df.groupby("item_purchased")["purchase_amount"].transform("mean")
)

df["purchase_amount"].isnull().sum()

np.int64(0)

In [31]:
# Verify missing values after handling null values

df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [32]:
# Check duplicate records in the dataset

df.duplicated().sum()

np.int64(50)

In [33]:
# Display duplicate rows

df[df.duplicated()].head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.3,No,Free Shipping,No,19.0,Cash,Monthly
1402,1621,25,Male,Hat,Accessories,47.0,Virginia,Free Size,Charcoal,Winter,3.1,No,2-Day Shipping,Yes,27.0,PayPal,Every 3 Months
1509,974,60,Male,Jacket,Outerwear,75.0,Colorado,M,Teal,Fall,3.5,Yes,2-Day Shipping,Yes,30.0,Bank Transfer,Quarterly
1600,2135,55,Male,Sandals,Footwear,41.0,Virginia,Not Available,Maroon,Winter,2.9,No,Standard,No,35.0,Credit Card,Fortnightly
1665,1846,51,Male,Sandals,Footwear,78.0,Delaware,Not Available,Orange,Winter,2.8,No,2-Day Shipping,No,39.0,Bank Transfer,Quarterly

In [34]:
# Check records for duplicate customer_id values

df[df["customer_id"] == 2834]

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
176,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.3,No,Free Shipping,No,19.0,Cash,Monthly
886,2834,43,Female,Jeans,Clothing,56.0,Arkansas,M,Teal,Fall,3.3,No,Free Shipping,No,19.0,Cash,Monthly

In [35]:
# Remove duplicate records based on customer_id and keep first occurrence

df = df.drop_duplicates(subset='customer_id', keep='first')

In [36]:
# Verify duplicate records after removal

df.duplicated().sum()

np.int64(0)

In [37]:
# Check final dataset shape after cleaning

print(f'Rows: {df.shape[0]}')
print(f'Columns: {df.shape[1]}')

Rows: 5000
Columns: 17

In [38]:
# 1. Initialize connection to local MySQL server

engine_server = create_engine(
    "mysql+pymysql://root:5233@localhost/"
)

# 2. Create project database if it does not exist

with engine_server.connect() as conn:
    conn.execute(
        text("CREATE DATABASE IF NOT EXISTS customer_shopping")
    )
    conn.commit()

print("Database customer_shopping created successfully")

Database customer_shopping created successfully

In [39]:
# 3. Connect specifically to the project database

engine = create_engine(
    "mysql+pymysql://root:5233@localhost/customer_shopping"
)

try:
    conn = engine.connect()
    print("Connected to customer_shopping successfully")
    conn.close()

except Exception as e:
    print(f"Connection failed: {e}")

Connected to customer_shopping successfully

In [40]:
# 4. Save cleaned dataset into MySQL table

df.to_sql(
    name="customer_sales",
    con=engine,
    if_exists="replace",
    index=False
)

print("Dataset saved to MySQL successfully")

Dataset saved to MySQL successfully

In [41]:
# Create inspector object for database inspection

inspector = inspect(engine)

In [42]:
# Display all tables present in the database

inspector.get_table_names()

['customer_sales']

In [43]:
# Save cleaned dataset to processed folder

df.to_csv("../data/processed/cleaned_customer_data.csv", index=False)

# Final Summary

The dataset has been successfully cleaned and preprocessed
for further analysis and database storage.

### Completed Data Cleaning Steps

- Handled missing values across multiple columns
- Standardized column names into snake_case format
- Corrected inconsistent category mappings
- Improved size value consistency across categories
- Verified duplicate customer IDs
- Enhanced overall data quality and consistency

### Database Integration

The cleaned dataset was successfully stored in a MySQL database,
and table structure was verified using SQLAlchemy Inspector.

### Outcome

The cleaned dataset is now ready for:
- SQL Analysis
- Business Analysis
- Data Visualization using Python
- Dashboard Creation in Power BI